Target Ruby 2.5.x for RuboCop and gemspec
It fixes the error:

Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion`
parameter (in .rubocop.yml). 2.4-compatible analysis was dropped after
version 1.12.